# --- Site ---
site_name: MkDocs
site_url: https://mkdocs.cublueprint.org
repo_url: https://github.com/carleton-blueprint/template-mkdocs

# --- Navigation ---
nav:
  - 'index.md'

# --- Extensions ---
plugins:
  - search
  - table-reader
  # - encryptcontent: # https://pypi.org/project/mkdocs-encryptcontent-plugin/#Usage
  #     global_password: !ENV [DOCS_PASSWORD, 'fallback_password_CUBLUEPRINT_2024']
  - social:
      cards_layout_options:
        background_color: '#0066db'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - def_list
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# --- Styles ---
theme:
  name: material
  logo: assets/images/logo_negative.png
  favicon: assets/images/square_bluebg.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    # - navigation.path # currently insiders only feature
  palette:
    # scheme: slate
    primary: custom
extra_css:
  - stylesheets/extra.css

# --- Footer ---
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Carleton-Blueprint
      name: Carleton Blueprint on GitHub
